### ISSUE TITLE
exampleのblockCodeでshikiのエラーが出る。

### ISSUE THREAD

**Issue by Hayao0819** [yamader/react-mfm#1]
```
PS C:\Users\hayao\Git\react-mfm> node --version
v18.19.0
PS C:\Users\hayao\Git\react-mfm> pnpm --version
8.14.1
PS C:\Users\hayao\Git\react-mfm>
```

```
> example@ dev C:\Users\hayao\Git\react-mfm\example
> next dev

   ▲ Next.js 14.1.0
   - Local:        http://localhost:3000

 ✓ Ready in 1740ms
 ○ Compiling / ...
 ✓ Compiled / in 1966ms (724 modules)
Error: ENOENT: no such file or directory, open '(ssr)\node_modules\.pnpm\vscode-oniguruma@1.7.0\node_modules\vscode-oniguruma\release\onig.wasm'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at getOniguruma (webpack-internal:///(ssr)/./node_modules/.pnpm/shiki@0.14.7/node_modules/shiki/dist/index.esm.js:2736:32)
    at getHighlighter (webpack-internal:///(ssr)/./node_modules/.pnpm/shiki@0.14.7/node_modules/shiki/dist/index.esm.js:3601:36)
    at highlighter (webpack-internal:///(ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/components/Code.js:34:73)
    at f (webpack-internal:///(ssr)/./node_modules/.pnpm/derive-valtio@0.1.0_valtio@1.13.0/node_modules/derive-valtio/dist/index.modern.js:75:36)
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/derive-valtio@0.1.0_valtio@1.13.0/node_modules/derive-valtio/dist/index.modern.js:100:9)
    at Array.forEach (<anonymous>)
    at f (webpack-internal:///(ssr)/./node_modules/.pnpm/derive-valtio@0.1.0_valtio@1.13.0/node_modules/derive-valtio/dist/index.modern.js:63:14)
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/components/Code.js:29:69)
    at (ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/components/Code.js (C:\Users\hayao\Git\react-mfm\example\.next\server\vendor-chunks\file+.._@types+react@18.2.48_react@18.2.0.js:60:1)
    at __webpack_require__ (C:\Users\hayao\Git\react-mfm\example\.next\server\webpack-runtime.js:33:42)        
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/Node.js:8:74)
    at (ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/Node.js (C:\Users\hayao\Git\react-mfm\example\.next\server\vendor-chunks\file+.._@types+react@18.2.48_react@18.2.0.js:40:1)
    at __webpack_require__ (C:\Users\hayao\Git\react-mfm\example\.next\server\webpack-runtime.js:33:42)        
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/index.js:14:63)
    at (ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/index.js (C:\Users\hayao\Git\react-mfm\example\.next\server\vendor-chunks\file+.._@types+react@18.2.48_react@18.2.0.js:140:1)
    at __webpack_require__ (C:\Users\hayao\Git\react-mfm\example\.next\server\webpack-runtime.js:33:42)        
    at eval (webpack-internal:///(ssr)/./app/(main)/page.tsx:9:67)
    at (ssr)/./app/(main)/page.tsx (C:\Users\hayao\Git\react-mfm\example\.next\server\app\(main)\page.js:316:1)
    at __webpack_require__ (C:\Users\hayao\Git\react-mfm\example\.next\server\webpack-runtime.js:33:42)        
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:103108
    at eo (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:103293)
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:105726
    at Object._fromJSON (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:106078)
    at JSON.parse (<anonymous>)
    at eu (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:103787)
    at en (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:102855)
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109661
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109678
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109711
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109728
    at t (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109951) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '(ssr)\\node_modules\\.pnpm\\vscode-oniguruma@1.7.0\\node_modules\\vscode-oniguruma\\release\\onig.wasm'
}
Error: ENOENT: no such file or directory, open '(ssr)\node_modules\.pnpm\vscode-oniguruma@1.7.0\node_modules\vscode-oniguruma\release\onig.wasm'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at getOniguruma (webpack-internal:///(ssr)/./node_modules/.pnpm/shiki@0.14.7/node_modules/shiki/dist/index.esm.js:2736:32)
    at getHighlighter (webpack-internal:///(ssr)/./node_modules/.pnpm/shiki@0.14.7/node_modules/shiki/dist/index.esm.js:3601:36)
    at highlighter (webpack-internal:///(ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/components/Code.js:34:73)
    at f (webpack-internal:///(ssr)/./node_modules/.pnpm/derive-valtio@0.1.0_valtio@1.13.0/node_modules/derive-valtio/dist/index.modern.js:75:36)
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/derive-valtio@0.1.0_valtio@1.13.0/node_modules/derive-valtio/dist/index.modern.js:100:9)
    at Array.forEach (<anonymous>)
    at f (webpack-internal:///(ssr)/./node_modules/.pnpm/derive-valtio@0.1.0_valtio@1.13.0/node_modules/derive-valtio/dist/index.modern.js:63:14)
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/components/Code.js:29:69)
    at (ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/components/Code.js (C:\Users\hayao\Git\react-mfm\example\.next\server\vendor-chunks\file+.._@types+react@18.2.48_react@18.2.0.js:60:1)
    at __webpack_require__ (C:\Users\hayao\Git\react-mfm\example\.next\server\webpack-runtime.js:33:42)        
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/Node.js:8:74)
    at (ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/Node.js (C:\Users\hayao\Git\react-mfm\example\.next\server\vendor-chunks\file+.._@types+react@18.2.48_react@18.2.0.js:40:1)
    at __webpack_require__ (C:\Users\hayao\Git\react-mfm\example\.next\server\webpack-runtime.js:33:42)        
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/index.js:14:63)
    at (ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/index.js (C:\Users\hayao\Git\react-mfm\example\.next\server\vendor-chunks\file+.._@types+react@18.2.48_react@18.2.0.js:140:1)
    at __webpack_require__ (C:\Users\hayao\Git\react-mfm\example\.next\server\webpack-runtime.js:33:42)        
    at eval (webpack-internal:///(ssr)/./app/(main)/page.tsx:9:67)
    at (ssr)/./app/(main)/page.tsx (C:\Users\hayao\Git\react-mfm\example\.next\server\app\(main)\page.js:316:1)
    at __webpack_require__ (C:\Users\hayao\Git\react-mfm\example\.next\server\webpack-runtime.js:33:42)        
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:103108
    at eo (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:103293)
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:105726
    at Object._fromJSON (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:106078)
    at JSON.parse (<anonymous>)
    at eu (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:103787)
    at en (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:102855)
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109661
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109678
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109711
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109728
    at t (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109951) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '(ssr)\\node_modules\\.pnpm\\vscode-oniguruma@1.7.0\\node_modules\\vscode-oniguruma\\release\\onig.wasm'
}
 ⨯ unhandledRejection: Error: ENOENT: no such file or directory, open '(ssr)\node_modules\.pnpm\vscode-oniguruma@1.7.0\node_modules\vscode-oniguruma\release\onig.wasm'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at getOniguruma (webpack-internal:///(ssr)/./node_modules/.pnpm/shiki@0.14.7/node_modules/shiki/dist/index.esm.js:2736:32)
    at getHighlighter (webpack-internal:///(ssr)/./node_modules/.pnpm/shiki@0.14.7/node_modules/shiki/dist/index.esm.js:3601:36)
    at highlighter (webpack-internal:///(ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/components/Code.js:34:73)
    at f (webpack-internal:///(ssr)/./node_modules/.pnpm/derive-valtio@0.1.0_valtio@1.13.0/node_modules/derive-valtio/dist/index.modern.js:75:36)
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/derive-valtio@0.1.0_valtio@1.13.0/node_modules/derive-valtio/dist/index.modern.js:100:9)
    at Array.forEach (<anonymous>)
    at f (webpack-internal:///(ssr)/./node_modules/.pnpm/derive-valtio@0.1.0_valtio@1.13.0/node_modules/derive-valtio/dist/index.modern.js:63:14)
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/components/Code.js:29:69)
    at (ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/components/Code.js (C:\Users\hayao\Git\react-mfm\example\.next\server\vendor-chunks\file+.._@types+react@18.2.48_react@18.2.0.js:60:1)
    at __webpack_require__ (C:\Users\hayao\Git\react-mfm\example\.next\server\webpack-runtime.js:33:42)        
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/Node.js:8:74)
    at (ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/Node.js (C:\Users\hayao\Git\react-mfm\example\.next\server\vendor-chunks\file+.._@types+react@18.2.48_react@18.2.0.js:40:1)
    at __webpack_require__ (C:\Users\hayao\Git\react-mfm\example\.next\server\webpack-runtime.js:33:42)        
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/index.js:14:63)
    at (ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/index.js (C:\Users\hayao\Git\react-mfm\example\.next\server\vendor-chunks\file+.._@types+react@18.2.48_react@18.2.0.js:140:1)
    at __webpack_require__ (C:\Users\hayao\Git\react-mfm\example\.next\server\webpack-runtime.js:33:42)        
    at eval (webpack-internal:///(ssr)/./app/(main)/page.tsx:9:67)
    at (ssr)/./app/(main)/page.tsx (C:\Users\hayao\Git\react-mfm\example\.next\server\app\(main)\page.js:316:1)
    at __webpack_require__ (C:\Users\hayao\Git\react-mfm\example\.next\server\webpack-runtime.js:33:42)        
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:103108
    at eo (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:103293)
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:105726
    at Object._fromJSON (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:106078)
    at JSON.parse (<anonymous>)
    at eu (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:103787)
    at en (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:102855)
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109661
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109678
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109711
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109728
    at t (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109951) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '(ssr)\\node_modules\\.pnpm\\vscode-oniguruma@1.7.0\\node_modules\\vscode-oniguruma\\release\\onig.wasm'
}
 ⨯ unhandledRejection: Error: ENOENT: no such file or directory, open '(ssr)\node_modules\.pnpm\vscode-oniguruma@1.7.0\node_modules\vscode-oniguruma\release\onig.wasm'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at getOniguruma (webpack-internal:///(ssr)/./node_modules/.pnpm/shiki@0.14.7/node_modules/shiki/dist/index.esm.js:2736:32)
    at getHighlighter (webpack-internal:///(ssr)/./node_modules/.pnpm/shiki@0.14.7/node_modules/shiki/dist/index.esm.js:3601:36)
    at highlighter (webpack-internal:///(ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/components/Code.js:34:73)
    at f (webpack-internal:///(ssr)/./node_modules/.pnpm/derive-valtio@0.1.0_valtio@1.13.0/node_modules/derive-valtio/dist/index.modern.js:75:36)
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/derive-valtio@0.1.0_valtio@1.13.0/node_modules/derive-valtio/dist/index.modern.js:100:9)
    at Array.forEach (<anonymous>)
    at f (webpack-internal:///(ssr)/./node_modules/.pnpm/derive-valtio@0.1.0_valtio@1.13.0/node_modules/derive-valtio/dist/index.modern.js:63:14)
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/components/Code.js:29:69)
    at (ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/components/Code.js (C:\Users\hayao\Git\react-mfm\example\.next\server\vendor-chunks\file+.._@types+react@18.2.48_react@18.2.0.js:60:1)
    at __webpack_require__ (C:\Users\hayao\Git\react-mfm\example\.next\server\webpack-runtime.js:33:42)        
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/Node.js:8:74)
    at (ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/Node.js (C:\Users\hayao\Git\react-mfm\example\.next\server\vendor-chunks\file+.._@types+react@18.2.48_react@18.2.0.js:40:1)
    at __webpack_require__ (C:\Users\hayao\Git\react-mfm\example\.next\server\webpack-runtime.js:33:42)        
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/index.js:14:63)
    at (ssr)/./node_modules/.pnpm/file+.._@types+react@18.2.48_react@18.2.0/node_modules/react-mfm/dist/index.js (C:\Users\hayao\Git\react-mfm\example\.next\server\vendor-chunks\file+.._@types+react@18.2.48_react@18.2.0.js:140:1)
    at __webpack_require__ (C:\Users\hayao\Git\react-mfm\example\.next\server\webpack-runtime.js:33:42)        
    at eval (webpack-internal:///(ssr)/./app/(main)/page.tsx:9:67)
    at (ssr)/./app/(main)/page.tsx (C:\Users\hayao\Git\react-mfm\example\.next\server\app\(main)\page.js:316:1)
    at __webpack_require__ (C:\Users\hayao\Git\react-mfm\example\.next\server\webpack-runtime.js:33:42)        
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:103108
    at eo (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:103293)
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:105726
    at Object._fromJSON (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:106078)
    at JSON.parse (<anonymous>)
    at eu (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:103787)
    at en (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:102855)
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109661
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109678
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109711
    at C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109728
    at t (C:\Users\hayao\Git\react-mfm\example\node_modules\.pnpm\next@14.1.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:109951) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '(ssr)\\node_modules\\.pnpm\\vscode-oniguruma@1.7.0\\node_modules\\vscode-oniguruma\\release\\onig.wasm'
}
[Error: ENOENT: no such file or directory, open 'C:\Users\hayao\Git\react-mfm\node_modules\.pnpm\shiki@0.14.7\node_modules\shiki\dist\themes\monokai.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\hayao\\Git\\react-mfm\\node_modules\\.pnpm\\shiki@0.14.7\\node_modules\\shiki\\dist\\themes\\monokai.json'
}
[Error: ENOENT: no such file or directory, open 'C:\Users\hayao\Git\react-mfm\node_modules\.pnpm\shiki@0.14.7\node_modules\shiki\dist\themes\monokai.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\hayao\\Git\\react-mfm\\node_modules\\.pnpm\\shiki@0.14.7\\node_modules\\shiki\\dist\\themes\\monokai.json'
}
 ⨯ unhandledRejection: [Error: ENOENT: no such file or directory, open 'C:\Users\hayao\Git\react-mfm\node_modules\.pnpm\shiki@0.14.7\node_modules\shiki\dist\themes\monokai.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\hayao\\Git\\react-mfm\\node_modules\\.pnpm\\shiki@0.14.7\\node_modules\\shiki\\dist\\themes\\monokai.json'
}
 ⨯ unhandledRejection: [Error: ENOENT: no such file or directory, open 'C:\Users\hayao\Git\react-mfm\node_modules\.pnpm\shiki@0.14.7\node_modules\shiki\dist\themes\monokai.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\hayao\\Git\\react-mfm\\node_modules\\.pnpm\\shiki@0.14.7\\node_modules\\shiki\\dist\\themes\\monokai.json'
}

```

![image](https://github.com/yamader/react-mfm/assets/32128205/4bbdd798-8b84-4b22-bfe2-3a06fed22336)

**Comment by yamader** [comment]
えっ本当だ
前まで動いてたのに

**Comment by yamader** [comment]
Windowsはsymlinkらへんが地雷そう

**Comment by yamader** [comment]
ごめん俺が悪かった，直ったか確認よろ

**Comment by Hayao0819** [comment]
うーん何も解決しない…
一旦pnpm辞めます

**Comment by yamader** [comment]
pnpm試してないや……

**Comment by yamader** [comment]
vscode-oniguruma足したので試してクレメンス

**Comment by yamader** [comment]
1.0.0にアプデしたので閉じますね
